<?php

namespace CH\PlatformBundle\Repository;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

use Doctrine\ORM\Tools\Pagination\Paginator;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

class AdvertRepository extends \Doctrine\ORM\EntityRepository
{

	public function getAdverts($page, $nbPerPage) {
		$query = $this->createQueryBuilder('a')
			->leftJoin('a.image', 'i')->addSelect('i')
			->leftJoin('a.categories', 'c')->addSelect('c')
			->orderBy('a.date', 'DESC')
			->getQuery();

		$query
			->setFirstResult(($page - 1)*$nbPerPage)
			->setMaxResults($nbPerPage);

		return new Paginator($query, true);
	}

	public function getAdvertWithCategories(array $categoryNames) {
		$qb=$this->createQueryBuilder('a');
		
		$qb->innerJoin('a.categories', 'c')->addSelect('c');

		$qb->where($qb->expr()->in('c.name', $categoryNames));

		return $qb->getQuery()->getResult();
	}

	public function myFindAll() {
		$qb=$this->createQueryBuilder('a');
		return $qb->getQuery()->getResult();
	}

	public function myFindBy($id) {
		$qb = $this->createQueryBuilder('a');
		$qb->where('a.id = :id')->setParameter('id', $id);

		return $qb->getQuery()->getResult();
	}

	public function findByAuthorAndDate($author, $year) {
		$qb = $this->createQueryBuilder('a');
		$qb->where('a.author = :author')->setParameter('author', $author);
		$qb->andWhere('a.date < :year')->setParameter('year', $year);
		$qb->orderBy('a.date', 'DESC');

		return $qb->getQuery()->getResult();
	}

	public function whereCurrentYear(QueryBuilder $qb) {
		$qb
		->andWhere('a.date BETWEEN :start AND :end')
		->setParameter('start', new \Datetime(date('Y').'-01-01'))
		->setParameter('end', new \Datetime(date('Y').'-12-31'))
		;
	}

	public function myFind() {
		$qb = $this->createQueryBuilder('a');

		$qb->where('a.author = :author')->setParameter('author', 'Nasser');

		$this->whereCurrentYear($qb);

		$qb->orderBy('a.date', 'DESC');

		return $qb->getQuery()->getResult();
	}
}
