parameters:
    app_webmaster: 'Clément Hayere'

services:
    ch_platform.antispam:
        class: CH\PlatformBundle\AntiSpam\CHAntiSpam
        arguments: 
            - "@mailer"
            - %mailer_transport%
            - 50

    ch_platform.email.application_mailer:
        class: CH\PlatformBundle\Email\ApplicationMailer
        arguments:
            - "@mailer"

    ch_platform.doctine_listener.application_creation_listener:
        class: CH\PlatformBundle\DoctrineListener\ApplicationCreationListener
        arguments:
            - "@ch_platform.email.application_mailer"
        tags:
            - { name: doctrine.event_listener, event: postPersist }
